### ISSUE TITLE
How to create const?

### ISSUE THREAD

**Issue by AkiKorpua** [lightsofapollo/joi-to-json-schema#32]
Seem's there is no support for const type in schema? I create following joi rule with only one valid value:

`myfield: Joi.equal('Ingredient').required()`

Now this is generated:
```
        "myfield": {
            "enum": [
                "Ingredient"
            ]
        }

```
What I would like to see:
```
        "myfield": {
            "const":  "Ingredient"
        }
```

Could this be doable?

**Comment by raisch** [comment]
What would the value be adding a new "const" type? If you can validate a field as a required enum with a single value, how would that differ from a "const"?

**Comment by raisch** [comment]
And for the record, 'const' really isn't a type, per se. It's a qualifier that indicates that a value of type T is immutable, irrespective of its type.

**Comment by AkiKorpua** [comment]
Ultimate goal here is to use joi notation to create dynamic json-schema to actually create form's with https://github.com/mozilla-services/react-jsonschema-form . On that there is difference in using Enum with only one option or Const.

As joi only give you synonyms like any.valid(value) - aliases: only, equal there is no exact keyword here.

For human it sounds like using keyword "only" would result in "const" but this is not valid assumption to Joi API.

Only way to find out that we really want const and not Enum is that there is only one option for valid/only/equal.

Does this sound like a hack?

**Comment by raisch** [comment]
While perhaps not exactly a hack, it does strike me that your request is
really an issue best addressed at the application-side rather than
something with which joi-to-json-schema should concern itself. So, I'm
happy to defer to James (lightsofapollo) on this.

--
Rob Raisch, Internaut and Technocrat

**Comment by AkiKorpua** [comment]
Let's solve this other way then.
