### ISSUE TITLE
joi.when requires an "is"

### ISSUE THREAD

**Issue by kaareal** [lightsofapollo/joi-to-json-schema#37]
The following seems to fall to convert:
```
const geoRectangle = {
  type: Joi.string()
    .valid('rectangle')
    .required(),
  geometry: {
    nw: Joi.object(geoPoint).required(),
    se: Joi.object(geoPoint).required()
  }
};

const geoPolygon = {
  type: Joi.string()
    .valid('polygon')
    .required(),
  geometry: {
    points: Joi.array()
      .min(3)
      .items(Joi.object(geoPoint))
  }
};

const geoShape = Joi.object()
  .when(Joi.object({ type: geoPolygon.type }), {
    then: Joi.object(geoPolygon)
  })
  .when(Joi.object({ type: geoRectangle.type }), {
    then: Joi.object(geoRectangle)
  })
```

fails with `joi.when requires an "is"`

Disabling the check for is converts things as expected, so thats nice. 

I see `https://github.com/lightsofapollo/joi-to-json-schema/blob/master/test/transformer_test.js#L79` does not cover the structure i wrote.

**Comment by lightsofapollo** [comment]
Not too familiar with this use-case . This is an area where we could honestly use some help. Would you be willing to contribute a fix or a test case (as PR) ?

**Comment by kaareal** [comment]
the code above doesn't quite work, so i am gonna close this one

**Comment by throrin19** [comment]
I have the same problem and I can explain that : 

the `when` must be use with 2 cases : 

- Directly with other object field
- With specific Joi schema

The problem with the second type. For example I have this schema : 

```js
Joi.when(Joi.object({ type : 'model' }).unknown(), {
    then        : Joi.object().keys(modelObject),
    otherwise   : Joi.object().keys(mathObject),
})
```

This schema switch full result schema when one specific field has specific value.

In my case, I can't use the `is` option but your library force this option and ignore the second `when` use case.
